version: '3.8'

services:
  api:
    build: ./services/api
    ports:
      - "4567:4567"
    environment:
      - RACK_ENV=production
      - DATABASE_URL=sqlite:///app/db/gemhub.db
      - API_TOKEN=${API_TOKEN:-default-token}
    volumes:
      - api_data:/app/db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4567/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Placeholder for Lane C services
  # sandbox_orch:
  #   build: ./services/sandbox_orch
  #   depends_on:
  #     - api

  # Placeholder for Lane D services
  # llm_gateway:
  #   build: ./services/llm_gateway
  #   environment:
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - MODEL=gpt-4o-mini
  #   ports:
  #     - "8000:8000"

  # vector_store:
  #   build: ./services/vector_store
  #   volumes:
  #     - vector_data:/app/data

volumes:
  api_data:
  # vector_data: 