# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in gemhub.gemspec
gemspec

group :development, :test do
  gem "rspec", "~> 3.12"
  gem "rubocop", "~> 1.57"
end
