source 'https://rubygems.org'

ruby '3.1.2'

gem 'sinatra', '~> 3.0'
gem 'sinatra-contrib'
gem 'sequel', '~> 5.0'
gem 'sqlite3', '~> 1.6'
gem 'json', '~> 2.6'
gem 'rack', '~> 2.2'
gem 'puma', '~> 6.0'
gem 'rack-contrib', '~> 2.4'

# Testing
group :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.0'
  gem 'json_matchers', '~> 0.11'
  gem 'factory_bot', '~> 6.4'
end

# Development
group :development do
  gem 'rerun', '~> 0.14'
end 